insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 12, "AC", "Acre", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 27, "AL", "Alagoas", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 16, "AP", "Amapá", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 13, "AM", "Amazonas", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 29, "BA", "Bahia", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 23, "CE", "Ceará", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 53, "DF", "Distrito Federal", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 32, "ES", "Espírito Santo", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 52, "GO", "Goiás", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 21, "MA", "Maranhão", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 51, "MT", "Mato Grosso", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 50, "MS", "Mato Grosso do Sul", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 31, "MG", "Minas Gerais", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 15, "PR", "Pará", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 25, "PB", "Paraíba", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 41, "PA", "Paraná", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 26, "PE", "Pernambuco", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 22, "PI", "Piauí", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 33, "RJ", "Rio de Janeiro", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 24, "RN", "Rio Grande do Norte", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 43, "RS", "Rio Grande do Sul", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 11, "RO", "Rondônia", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 14, "RR", "Roraima", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 42, "SC", "Santa Catarina", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 35, "SE", "São Paulo", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 28, "SP", "Sergipe", 1, "S");
insert into localizacao (localizacao_tipo_id, codigo, sigla, nome, localizacao_id, padrao) values (5, 17, "TO", "Tocantins", 1, "S");