insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Brasil", "BR", null, null, "S");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Afeganistão", "AF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Albânia", "AL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Alemanha", "DE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Andorra", "AD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Angola", "AO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Anguilla", "AI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Antilhas Holandesas", "AN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Antártida", "AQ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Antígua e Barbuda", "AG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Argentina", "AR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Argélia", "DZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Armênia", "AM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Aruba", "AW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Arábia Saudita", "SA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Austrália", "AU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Azerbaijão", "AZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bahamas", "BS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bahrein", "BH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bangladesh", "BD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Barbados", "BB", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Belarus", "BY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Belize", "BZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Benin", "BJ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bermudas", "BM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bolívia", "BO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Botsuana", "BW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Brunei", "BN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bulgária", "BG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Burkina Fasso", "BF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Burundi", "BI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Butão", "BT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bélgica", "BE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Bósnia-Herzegóvina", "BA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Cabo Verde", "CV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Camarões", "CM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Camboja", "KH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Canadá", "CA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Cazaquistão", "KZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Chade", "TD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Chile", "CL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "China", "CN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Chipre", "CY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Cingapura", "SG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Colômbia", "CO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Congo", "CG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Coréia do Norte", "KP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Coréia do Sul", "KR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Costa Rica", "CR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Costa do Marfim", "CI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Croácia (Hrvatska)", "HR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Cuba", "CU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Dinamarca", "DK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Djibuti", "DJ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Dominica", "DM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Egito", "EG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "El Salvador", "SV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Emirados Árabes Unidos", "AE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Equador", "EC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Eritréia", "ER", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Eslováquia", "SK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Eslovênia", "SI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Espanha", "ES", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Estados Unidos", "US", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Estônia", "EE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Etiópia", "ET", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Federação Russa", "RU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Fiji", "FJ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Filipinas", "PH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Finlândia", "FI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "França", "FR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Gabão", "GA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Gana", "GH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Geórgia", "GE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Gibraltar", "GI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Granada", "GD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Groelândia", "GL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Grã-Bretanha (Reino Unido, Inglaterra)", "GB", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Grécia", "GR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guadalupe", "GP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guam (Território dos Estados Unidos)", "GU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guatemala", "GT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guernsey", "G", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guiana Francesa", "GF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guiana", "GY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guiné Equatorial", "GQ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guiné", "GN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Guiné-Bissau", "GW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Gâmbia", "GM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Haiti", "HT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Holanda", "NL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Honduras", "HN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Hong Kong", "HK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Hungria", "HU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilha Bouvet (Território da Noruega)", "BV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilha Natal", "CX", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilha Pitcairn", "PN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilha Reunião", "RE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilha do Homem", "IM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Aland", "AX", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Cayman", "KY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Cocos", "CC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Comores", "KM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Cook", "CK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Falkland (Malvinas)", "FK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Faroes", "FO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Geórgia do Sul e Sandwich do Sul", "GS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Heard e McDonald (Território da Austrália)", "HM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Marianas do Norte", "MP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Marshall", "MH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Menores dos Estados Unidos", "UM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Norfolk", "NF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Seychelles", "SC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Solomão", "SB", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Svalbard e Jan Mayen", "SJ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Tokelau", "TK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Turks e Caicos", "TC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Virgens (Estados Unidos)", "VI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Virgens (Inglaterra)", "VG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ilhas Wallis e Futuna", "WF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Indonésia", "ID", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Iraque", "IQ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Irlanda", "IE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Irã", "IR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Islândia", "IS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Israel", "IL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Itália", "IT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Iêmen", "YE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Jamaica", "JM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Japão", "JP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Jersey", "JE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Jordânia", "JO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Kiribati", "KI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Kuait", "KW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Kênia", "KE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Laos", "LA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Lesoto", "LS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Libéria", "LR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Liechtenstein", "LI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Lituânia", "LT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Luxemburgo", "LU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Látvia", "LV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Líbano", "LB", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Líbia", "LY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Macau", "MO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Macedônia (República Yugoslava)", "MK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Madagascar", "MG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Malaui", "MW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Maldivas", "MV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Mali", "ML", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Malta", "MT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Malásia", "MY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Marrocos", "MA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Martinica", "MQ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Mauritânia", "MR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Maurício", "MU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Mayotte", "YT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Micronésia", "FM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Moldova", "MD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Mongólia", "MN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Montenegro", "ME", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Montserrat", "MS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Moçambique", "MZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Myanma", "MM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "México", "MX", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Mônaco", "MC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Namíbia", "NA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nauru", "NR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nepal", "NP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nicarágua", "NI", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nigéria", "NG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Niue", "NU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Noruega", "NO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nova Caledônia", "NC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Nova Zelândia", "NZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Níger", "NE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Omã", "OM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Palau", "PW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Panamá", "PA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Papua-Nova Guiné", "PG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Paquistão", "PK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Paraguai", "PY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Peru", "PE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Polinésia Francesa", "PF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Polônia", "PL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Porto Rico", "PR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Portugal", "PT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Qatar", "QA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Quirguistão", "KG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "República Centro-Africana", "CF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "República Democrática do Congo", "CD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "República Dominicana", "DO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "República Tcheca", "CZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Romênia", "RO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ruanda", "RW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Saara Ocidental", "EH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Saint Vincente e Granadinas", "VC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Samoa Ocidental", "AS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Samoa Ocidental", "WS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "San Marino", "SM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Santa Helena", "SH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Santa Lúcia", "LC", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Senegal", "SN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Serra Leoa", "SL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Somália", "SO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Sri Lanka", "LK", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "St. Pierre and Miquelon", "PM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Suazilândia", "SZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Sudão", "SD", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Suriname", "SR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Suécia", "SE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Suíça", "CH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "São Bartolomeu", "BL", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "São Cristóvão e Névis", "KN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "São Martim", "MF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "São Tomé e Príncipe", "ST", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Sérvia", "RS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Síria", "SY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tadjiquistão", "TJ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tailândia", "TH", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Taiwan", "TW", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tanzânia", "TZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Território Britânico do Oceano índico", "IO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Territórios Palestinos Ocupados", "PS", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Territórios do Sul da França", "TF", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Timor Leste", "TP", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Togo", "TG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tonga", "TO", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Trinidad and Tobago", "TT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tunísia", "TN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Turcomenistão", "TM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Turquia", "TR", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Tuvalu", "TV", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Ucrânia", "UA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Uganda", "UG", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Uruguai", "UY", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Uzbequistão", "UZ", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Vanuatu", "VU", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Vaticano", "VA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Venezuela", "VE", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Vietnã", "VN", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Zâmbia", "ZM", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "África do Sul", "ZA", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "Áustria", "AT", null, null, "N");
insert into pessoa.localizacao (localizacao_tipo_id, nome, sigla, codigo, localizacao_id, padrao) values (4, "índia", "IN", null, null, "N");